apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: storefront-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      serviceAccountName: CLOUD_RUN_SERVICE_ACCOUNT@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/frontend:TAG
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: https://api-gateway-xxxxx-uc.a.run.app/api
